name: Release Extension

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tag')
    steps:
      - uses: actions/checkout@v2
      - name: Build extension
        run: yarn build
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
